export const events = [
  {
    _id: "19829842ibhass",
    name: "Colors Festival",
    img_url: "/images/event-example1.jpeg",
    date: "2025-06-15T18:00:00Z",
    location: "Sports Complex",
    prices: {
      regular: 2000,
      vip: 5000,
    },
    description:
      "Join us for an unforgettable evening filled with music, dance, and vibrant colors. Celebrate with your fellow AFIT students!",
    host: "AFIT Student Union",
    capacity: 500,
    tickets_sold: 120,
    category: "Music & Culture",
    is_featured: true,
    age_restriction: "16+",
    tags: ["music", "festival", "color party", "campus"],
    status: "upcoming",
  },
  {
    _id: "23982374abcxyz",
    name: "Tech Innovators Meetup",
    img_url: "/images/event-example2.jpeg",
    date: "2025-07-05T10:00:00Z",
    location: "Main Auditorium",
    prices: {
      regular: 0,
      vip: 1000,
    },
    description:
      "Connect with tech enthusiasts, developers, and innovators in AFIT. Explore exciting projects, talks, and networking opportunities.",
    host: "AFIT Tech Hub",
    capacity: 300,
    tickets_sold: 220,
    category: "Conference & Tech",
    is_featured: true,
    age_restriction: "None",
    tags: ["tech", "networking", "startups", "developers"],
    status: "upcoming",
  },
  {
    _id: "99828377dfgtyu",
    name: "AFIT Movie Night",
    img_url: "/images/event-example3.jpeg",
    date: "2025-06-20T19:30:00Z",
    location: "Open Air Theater",
    prices: {
      regular: 500,
      vip: 1500,
    },
    description:
      "Enjoy a fun movie night under the stars with friends and snacks. Vote on which movie will be screened!",
    host: "AFIT Entertainment Club",
    capacity: 400,
    tickets_sold: 280,
    category: "Entertainment",
    is_featured: false,
    age_restriction: "13+",
    tags: ["movie", "nightlife", "snacks", "relax"],
    status: "upcoming",
  },
  {
    _id: "32419824qweops",
    name: "Cultural Day Fiesta",
    img_url: "/images/event-example4.jpeg",
    date: "2025-08-01T13:00:00Z",
    location: "Central Parade Ground",
    prices: {
      regular: 1000,
      vip: 3000,
    },
    description:
      "Experience the diverse cultures of Nigeria with traditional dances, food, and fashion. A showcase of AFIT's cultural heritage.",
    host: "AFIT Cultural Society",
    capacity: 600,
    tickets_sold: 430,
    category: "Culture & Community",
    is_featured: true,
    age_restriction: "None",
    tags: ["culture", "food", "fashion", "tradition"],
    status: "upcoming",
  },
];

export const categories = [
  { value: "", label: "Select a category" },
  { value: "conference", label: "Conference" },
  { value: "workshop", label: "Workshop" },
  { value: "seminar", label: "Seminar" },
  { value: "party", label: "Party/Social Gathering" },
  { value: "concert", label: "Concert/Performance" },
  { value: "exhibition", label: "Exhibition" },
  { value: "fundraiser", label: "Fundraiser" },
  { value: "sports", label: "Sports Event" },
  { value: "other", label: "Other" },
];
